name: accessibility
on: [push]
jobs:
  cypress-axe:
    name: cypress-axe
    runs-on: ubuntu-20.04
    env:
      MAAS_URL: http://localhost:5240
    steps:
      - uses: actions/checkout@main
      - name: Get branch name
        uses: nelonoel/branch-name@v1.0.1
      - name: Install MAAS
        run: |
          sudo systemctl enable snapd
          sudo snap install maas --channel=latest/edge
          sudo snap install maas-test-db --channel=latest/edge
      - name: Initialise MAAS
        run: sudo maas init region+rack --maas-url=${{env.MAAS_URL}}/MAAS --database-uri maas-test-db:///
      - name: Install Cypress
        uses: cypress-io/github-action@v4
        with:
          runTests: false
      - name: Create MAAS admin
        run: sudo maas createadmin --username=admin --password=test --email=fake@example.org
      - name: Run cypress-axe accessibility tests
        uses: cypress-io/github-action@v4
        with:
          config: baseUrl=${{env.MAAS_URL}},pageLoadTimeout=100000
          install: false
          spec: "cypress/e2e/accessibility/**/*.spec.ts"
          wait-on: "${{env.MAAS_URL}}/MAAS/r/machines"
      - name: Create issue on failure
        if: failure()
        uses: JasonEtco/create-an-issue@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REPO: ${{ github.repository }}
          RUN_ID: ${{ github.run_id }}
        with:
          filename: .github/ISSUE_TEMPLATE/accessibility-failure.md
          update_existing: true
