name: "Lint PR"

on:
  pull_request:
    types: [opened, edited, synchronize, reopened]

permissions:
  pull-requests: read

jobs:
  main:
    name: Validate PR title
    runs-on: ubuntu-24.04
    steps:
      - uses: amannn/action-semantic-pull-request@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          scopes: |
            api
            base
            controllers
            deps
            deps-dev
            devices
            domains
            images
            intro
            kvm
            machines
            networkDiscovery
            networks
            pools
            preferences
            racks
            settings
            store
            tags
            utils
            zones
