name: Upload
on:
  pull_request_target:
    types: [closed]
jobs:
  upload-build:
    if: github.event.pull_request.merged == true
    name: Upload build artifacts
    runs-on: ubuntu-22.04
    env:
      PACKAGE_NAME: maas-ui-${{ github.sha }}.tar.gz
      REACT_APP_GIT_SHA: ${{ github.sha }}
    strategy:
      matrix:
        node-version: [16.x]
    steps:
      - uses: actions/checkout@v3
      - name: Get branch name
        uses: nelonoel/branch-name@v1.0.1
      - name: Restore node_modules
        id: yarn-cache
        uses: actions/cache@v3
        with:
          path: "**/node_modules"
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install
        if: steps.yarn-cache.outputs.cache-hit != 'true'
        run: CYPRESS_INSTALL_BINARY=0 yarn install
      - name: Build
        run: REACT_APP_GIT_SHA=${{env.REACT_APP_GIT_SHA}} GENERATE_SOURCEMAP=false yarn build
        env:
          CI: false
      - name: Compress
        run: cd build && tar -czf ../${{env.PACKAGE_NAME}} ./
      - name: Install upload-assets snap
        run: sudo snap install upload-assets
      - name: Upload to assets server
        run: upload-assets --url-path ${{env.PACKAGE_NAME}} ${{env.PACKAGE_NAME}}
        env:
          UPLOAD_ASSETS_API_TOKEN: ${{secrets.UPLOAD_ASSETS_API_TOKEN}}
      - name: Create issue on failure
        if: failure()
        uses: JasonEtco/create-an-issue@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REPO: ${{ github.repository }}
          RUN_ID: ${{ github.run_id }}
        with:
          filename: .github/ISSUE_TEMPLATE/upload-failure.md
          update_existing: true
